/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ColdEmailRequest = IDL.Record({
  'personalization' : IDL.Text,
  'subject' : IDL.Text,
  'companySector' : IDL.Text,
  'useCase' : IDL.Text,
  'recipient' : IDL.Text,
  'meetingRequest' : IDL.Text,
  'targetCompany' : IDL.Text,
  'productDetails' : IDL.Text,
});
export const ColdEmailResponse = IDL.Record({
  'finalOutput' : IDL.Text,
  'subjectLines' : IDL.Vec(IDL.Text),
  'mainEmail' : IDL.Text,
  'followUp1' : IDL.Text,
  'followUp2' : IDL.Text,
});
export const SeoPackRequest = IDL.Record({
  'mainTopic' : IDL.Text,
  'videoTitle' : IDL.Text,
});
export const SeoPackResponse = IDL.Record({
  'titles' : IDL.Vec(IDL.Text),
  'hashtags' : IDL.Vec(IDL.Text),
  'tags' : IDL.Vec(IDL.Text),
  'pinnedComment' : IDL.Text,
  'description' : IDL.Text,
  'chapters' : IDL.Vec(IDL.Text),
});
export const Language = IDL.Variant({
  'ar' : IDL.Null,
  'de' : IDL.Null,
  'en' : IDL.Null,
  'es' : IDL.Null,
  'fr' : IDL.Null,
  'hi' : IDL.Null,
  'it' : IDL.Null,
  'ja' : IDL.Null,
  'ko' : IDL.Null,
  'pt' : IDL.Null,
  'ru' : IDL.Null,
  'zh' : IDL.Null,
});
export const SubtitleStyle = IDL.Variant({
  'mrbeastStyle' : IDL.Null,
  'bold' : IDL.Null,
  'simple' : IDL.Null,
});
export const SubtitleRequest = IDL.Record({
  'script' : IDL.Text,
  'language' : Language,
  'style' : SubtitleStyle,
});
export const ContentRequest = IDL.Record({
  'includeSubtitles' : IDL.Bool,
  'createScript' : IDL.Bool,
  'voiceLanguage' : Language,
  'scriptLanguage' : Language,
  'autoTranslateSubtitles' : IDL.Bool,
  'subtitleLanguage' : Language,
});
export const VideoRequest = IDL.Record({
  'creator' : IDL.Principal,
  'mainTopic' : IDL.Text,
  'requirements' : ContentRequest,
  'videoTitle' : IDL.Text,
});
export const AnimationPlan = IDL.Record({ 'steps' : IDL.Vec(IDL.Text) });
export const Storyboard = IDL.Record({ 'scenes' : IDL.Vec(IDL.Text) });
export const ExportPlan = IDL.Record({
  'outputDestination' : IDL.Text,
  'animationPlan' : AnimationPlan,
  'script' : IDL.Text,
  'compressionMethod' : IDL.Text,
  'storyboard' : Storyboard,
  'exportFormat' : IDL.Text,
  'qualityLevel' : IDL.Text,
});
export const VideoResponse = IDL.Record({
  'animationPlan' : AnimationPlan,
  'script' : IDL.Text,
  'storyboard' : Storyboard,
  'exportPlan' : ExportPlan,
  'subtitles' : IDL.Vec(IDL.Text),
});
export const Emotion = IDL.Variant({
  'normal' : IDL.Null,
  'energetic' : IDL.Null,
  'serious' : IDL.Null,
});
export const VoiceSpeed = IDL.Variant({
  'normal' : IDL.Null,
  'fast' : IDL.Null,
  'slow' : IDL.Null,
});
export const VoiceGender = IDL.Variant({
  'female' : IDL.Null,
  'male' : IDL.Null,
});
export const VoiceoverRequest = IDL.Record({
  'emotion' : Emotion,
  'script' : IDL.Text,
  'language' : Language,
  'speed' : VoiceSpeed,
  'voiceGender' : VoiceGender,
});
export const ChatRole = IDL.Variant({
  'user' : IDL.Null,
  'assistant' : IDL.Null,
});
export const Message = IDL.Record({
  'height' : IDL.Opt(IDL.Nat),
  'content' : IDL.Text,
  'role' : ChatRole,
  'timestamp' : IDL.Int,
  'imageBytes' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  'width' : IDL.Opt(IDL.Nat),
});
export const ImageGenerationParams = IDL.Record({
  'model' : IDL.Text,
  'guidanceScale' : IDL.Float64,
  'seed' : IDL.Nat64,
  'steps' : IDL.Nat,
  'samplerMethod' : IDL.Text,
  'imageBase64' : IDL.Text,
  'prompt' : IDL.Text,
  'negativePrompt' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'principal' : IDL.Principal,
  'displayName' : IDL.Text,
  'avatar' : IDL.Text,
});
export const TransactionType = IDL.Variant({
  'credit' : IDL.Null,
  'featureUsage' : IDL.Null,
  'debit' : IDL.Null,
});
export const TransactionRecord = IDL.Record({
  'principal' : IDL.Principal,
  'feature' : IDL.Text,
  'transactionType' : TransactionType,
  'timestamp' : IDL.Int,
  'balanceAfter' : IDL.Nat,
  'amount' : IDL.Nat,
});
export const CoinPurchasePlan = IDL.Record({
  'id' : IDL.Nat,
  'coinAmount' : IDL.Nat,
  'name' : IDL.Text,
  'price' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'chargeFeatureUsage' : IDL.Func([IDL.Text], [], []),
  'clearChatHistory' : IDL.Func([], [], []),
  'generateColdEmail' : IDL.Func([ColdEmailRequest], [ColdEmailResponse], []),
  'generateSeoPack' : IDL.Func([SeoPackRequest], [SeoPackResponse], []),
  'generateSubtitles' : IDL.Func([SubtitleRequest], [IDL.Text], []),
  'generateVideoResponse' : IDL.Func([VideoRequest], [VideoResponse], []),
  'generateVoiceover' : IDL.Func([VoiceoverRequest], [IDL.Text], []),
  'getAllChatHistories' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(Message)))],
      ['query'],
    ),
  'getAllImageGenerationParams' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(ImageGenerationParams)))],
      ['query'],
    ),
  'getAppInfo' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChatHistory' : IDL.Func([], [IDL.Opt(IDL.Vec(Message))], []),
  'getCoinBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'getCurrentTime' : IDL.Func([], [IDL.Int], ['query']),
  'getImageGenerationParams' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(IDL.Vec(ImageGenerationParams))],
      ['query'],
    ),
  'getTransactionHistory' : IDL.Func(
      [],
      [IDL.Vec(TransactionRecord)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listCoinPurchasePlans' : IDL.Func(
      [],
      [IDL.Vec(CoinPurchasePlan)],
      ['query'],
    ),
  'processChatMessage' : IDL.Func([Message], [IDL.Vec(Message)], []),
  'purchaseCoins' : IDL.Func([IDL.Nat], [IDL.Nat], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitImageGenerationParams' : IDL.Func([ImageGenerationParams], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ColdEmailRequest = IDL.Record({
    'personalization' : IDL.Text,
    'subject' : IDL.Text,
    'companySector' : IDL.Text,
    'useCase' : IDL.Text,
    'recipient' : IDL.Text,
    'meetingRequest' : IDL.Text,
    'targetCompany' : IDL.Text,
    'productDetails' : IDL.Text,
  });
  const ColdEmailResponse = IDL.Record({
    'finalOutput' : IDL.Text,
    'subjectLines' : IDL.Vec(IDL.Text),
    'mainEmail' : IDL.Text,
    'followUp1' : IDL.Text,
    'followUp2' : IDL.Text,
  });
  const SeoPackRequest = IDL.Record({
    'mainTopic' : IDL.Text,
    'videoTitle' : IDL.Text,
  });
  const SeoPackResponse = IDL.Record({
    'titles' : IDL.Vec(IDL.Text),
    'hashtags' : IDL.Vec(IDL.Text),
    'tags' : IDL.Vec(IDL.Text),
    'pinnedComment' : IDL.Text,
    'description' : IDL.Text,
    'chapters' : IDL.Vec(IDL.Text),
  });
  const Language = IDL.Variant({
    'ar' : IDL.Null,
    'de' : IDL.Null,
    'en' : IDL.Null,
    'es' : IDL.Null,
    'fr' : IDL.Null,
    'hi' : IDL.Null,
    'it' : IDL.Null,
    'ja' : IDL.Null,
    'ko' : IDL.Null,
    'pt' : IDL.Null,
    'ru' : IDL.Null,
    'zh' : IDL.Null,
  });
  const SubtitleStyle = IDL.Variant({
    'mrbeastStyle' : IDL.Null,
    'bold' : IDL.Null,
    'simple' : IDL.Null,
  });
  const SubtitleRequest = IDL.Record({
    'script' : IDL.Text,
    'language' : Language,
    'style' : SubtitleStyle,
  });
  const ContentRequest = IDL.Record({
    'includeSubtitles' : IDL.Bool,
    'createScript' : IDL.Bool,
    'voiceLanguage' : Language,
    'scriptLanguage' : Language,
    'autoTranslateSubtitles' : IDL.Bool,
    'subtitleLanguage' : Language,
  });
  const VideoRequest = IDL.Record({
    'creator' : IDL.Principal,
    'mainTopic' : IDL.Text,
    'requirements' : ContentRequest,
    'videoTitle' : IDL.Text,
  });
  const AnimationPlan = IDL.Record({ 'steps' : IDL.Vec(IDL.Text) });
  const Storyboard = IDL.Record({ 'scenes' : IDL.Vec(IDL.Text) });
  const ExportPlan = IDL.Record({
    'outputDestination' : IDL.Text,
    'animationPlan' : AnimationPlan,
    'script' : IDL.Text,
    'compressionMethod' : IDL.Text,
    'storyboard' : Storyboard,
    'exportFormat' : IDL.Text,
    'qualityLevel' : IDL.Text,
  });
  const VideoResponse = IDL.Record({
    'animationPlan' : AnimationPlan,
    'script' : IDL.Text,
    'storyboard' : Storyboard,
    'exportPlan' : ExportPlan,
    'subtitles' : IDL.Vec(IDL.Text),
  });
  const Emotion = IDL.Variant({
    'normal' : IDL.Null,
    'energetic' : IDL.Null,
    'serious' : IDL.Null,
  });
  const VoiceSpeed = IDL.Variant({
    'normal' : IDL.Null,
    'fast' : IDL.Null,
    'slow' : IDL.Null,
  });
  const VoiceGender = IDL.Variant({ 'female' : IDL.Null, 'male' : IDL.Null });
  const VoiceoverRequest = IDL.Record({
    'emotion' : Emotion,
    'script' : IDL.Text,
    'language' : Language,
    'speed' : VoiceSpeed,
    'voiceGender' : VoiceGender,
  });
  const ChatRole = IDL.Variant({ 'user' : IDL.Null, 'assistant' : IDL.Null });
  const Message = IDL.Record({
    'height' : IDL.Opt(IDL.Nat),
    'content' : IDL.Text,
    'role' : ChatRole,
    'timestamp' : IDL.Int,
    'imageBytes' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'width' : IDL.Opt(IDL.Nat),
  });
  const ImageGenerationParams = IDL.Record({
    'model' : IDL.Text,
    'guidanceScale' : IDL.Float64,
    'seed' : IDL.Nat64,
    'steps' : IDL.Nat,
    'samplerMethod' : IDL.Text,
    'imageBase64' : IDL.Text,
    'prompt' : IDL.Text,
    'negativePrompt' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'principal' : IDL.Principal,
    'displayName' : IDL.Text,
    'avatar' : IDL.Text,
  });
  const TransactionType = IDL.Variant({
    'credit' : IDL.Null,
    'featureUsage' : IDL.Null,
    'debit' : IDL.Null,
  });
  const TransactionRecord = IDL.Record({
    'principal' : IDL.Principal,
    'feature' : IDL.Text,
    'transactionType' : TransactionType,
    'timestamp' : IDL.Int,
    'balanceAfter' : IDL.Nat,
    'amount' : IDL.Nat,
  });
  const CoinPurchasePlan = IDL.Record({
    'id' : IDL.Nat,
    'coinAmount' : IDL.Nat,
    'name' : IDL.Text,
    'price' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'chargeFeatureUsage' : IDL.Func([IDL.Text], [], []),
    'clearChatHistory' : IDL.Func([], [], []),
    'generateColdEmail' : IDL.Func([ColdEmailRequest], [ColdEmailResponse], []),
    'generateSeoPack' : IDL.Func([SeoPackRequest], [SeoPackResponse], []),
    'generateSubtitles' : IDL.Func([SubtitleRequest], [IDL.Text], []),
    'generateVideoResponse' : IDL.Func([VideoRequest], [VideoResponse], []),
    'generateVoiceover' : IDL.Func([VoiceoverRequest], [IDL.Text], []),
    'getAllChatHistories' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(Message)))],
        ['query'],
      ),
    'getAllImageGenerationParams' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(ImageGenerationParams)))],
        ['query'],
      ),
    'getAppInfo' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChatHistory' : IDL.Func([], [IDL.Opt(IDL.Vec(Message))], []),
    'getCoinBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getCurrentTime' : IDL.Func([], [IDL.Int], ['query']),
    'getImageGenerationParams' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(IDL.Vec(ImageGenerationParams))],
        ['query'],
      ),
    'getTransactionHistory' : IDL.Func(
        [],
        [IDL.Vec(TransactionRecord)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listCoinPurchasePlans' : IDL.Func(
        [],
        [IDL.Vec(CoinPurchasePlan)],
        ['query'],
      ),
    'processChatMessage' : IDL.Func([Message], [IDL.Vec(Message)], []),
    'purchaseCoins' : IDL.Func([IDL.Nat], [IDL.Nat], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitImageGenerationParams' : IDL.Func([ImageGenerationParams], [], []),
  });
};

export const init = ({ IDL }) => { return []; };